name: Build Check

on:
  push:
    paths:
    - 'Client/**'
    - 'Server/**'
    - 'GameEngine/**'
    - 'CMakeLists.txt'
  pull_request:
    paths:
    - 'Client/**'
    - 'Server/**'
    - 'GameEngine/**'
    - 'CMakeLists.txt'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Windows Latest, os: windows-latest }
          # - { name: Linux GCC,      os: ubuntu-latest }
          # - { name: Linux Clang, os: ubuntu-latest, flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }

    steps:
      - name: Install Boost on Windows
        if: runner.os == 'Windows'
        run: |
          Invoke-WebRequest -Uri https://boostorg.jfrog.io/artifactory/main/release/1.84.0/source/boost_1_84_0.zip -OutFile boost.zip
          Expand-Archive -Path boost.zip -DestinationPath C:\boost
          Remove-Item -Path boost.zip


      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libxrandr-dev libxcursor-dev libudev-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev libfreetype6 libfreetype6-dev cmake clang-tidy

      - name: Install clang-format 16
        if: runner.os == 'Linux'
        shell: bash
        run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 16 && sudo apt install clang-format-16 && if [ ! -e /usr/bin/clang-format ]; then sudo ln -s /usr/bin/clang-format-16 /usr/bin/clang-format; fi

      - name: Install Boost
        if: runner.os == 'Linux'
        run: sudo apt-get install -y libboost-all-dev

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        shell: bash
        run: cmake -S . -B build -DCMAKE_INSTALL_PREFIX=install ${{matrix.platform.flags}}

      - name: Build
        shell: bash
        run: cmake --build build --config Release

      - name: Install
        shell: bash
        run: cmake --install build --config Release

