name: Build Check

on:
  push:
    paths:
    - 'Client/**'
    - 'Server/**'
    - 'ECS/**'
    - 'CMakeLists.txt'
  pull_request:
    paths:
    - 'Client/**'
    - 'Server/**'
    - 'ECS/**'
    - 'CMakeLists.txt'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        # - { name: Windows Latest, os: windows-latest }
          - { name: Linux GCC,      os: ubuntu-latest }
          # - { name: Linux Clang, os: ubuntu-latest, flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }

    steps:
      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libxrandr-dev libxcursor-dev libudev-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev cmake clang-format clang-tidy

      - name: Install Boost
        if: runner.os == 'Linux'
        run: sudo apt-get install -y libboost-all-dev

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        shell: bash
        run: cmake -S . -B build -DCMAKE_INSTALL_PREFIX=install ${{matrix.platform.flags}}

      - name: Build
        shell: bash
        run: cmake --build build --config Release

      - name: Install
        shell: bash
        run: cmake --install build --config Release

