name: Deploy to Epitech repository

on:
  workflow_run:
    workflows: ["Build Check"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' && 
      github.repository != 'EpitechPromo2026/B-CPP-500-BDX-5-2-rtype-jules.trolle'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:EpitechPromo2026/B-CPP-500-BDX-5-2-rtype-jules.trolle.git
          ssh_private_key: ${{ secrets.ACTION_GITHUB }}

