name: Deploy to Epitech repository

on:
  workflow_run:
    workflows: ["Build Check"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'ssh://git@github.com/EpitechPromo2026/B-CPP-500-BDX-5-2-rtype-jules.trolle.git'
          GIT_SSH_PRIVATE_KEY: ${{ secrets.ACTION_GITHUB }}
          GIT_SSH_NO_VERIFY_HOST: "true"
